Javascript Module - To Do List: List structure submission
yigitm/todo-list pull request #1
Opened 2021-11-30 20:56 UTC by yigitm

Below features/configurations are added;

- Webpack project set-up
- HTML Webpack Plugin set-up
- Webpack Style/CSS Loader set-up
- When document loaded createTask() function is populating tasks array elements
- General document style is added

Thank you for your time.

2021-11-30 21:17 UTC, mikethreels requested changes
Hi Yiğit, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 21:17 UTC, mikethreels commented on dist/index.html
>      <meta charset="UTF-8" />
- [ ] great start setting up the project 👍 however the `npm start` command is not working because the `webpack-dev-server` package is not included in your `package.json` file

2021-11-30 21:17 UTC, mikethreels commented on src/index.js
> +const tasks = [];
- [ ] According to the requirements you should create an **index.js** file and set an array of some simple *to do tasks* (array of objects). Each task object should contain three keys: 
  1. description [`string`].
  2. completed [`bool`].
  3. index: [`number`].
this means that the array should contain some placeholder to-do items.

2021-12-01 00:14 UTC, yigitm commented on dist/index.html
>      <meta charset="UTF-8" />
Thank you. It installed.

2021-12-01 00:16 UTC, yigitm commented on src/index.js
> +const tasks = [];
Change the function in order to view the initial key & values as mentioned: description, completed, index.

2021-12-01 00:45 UTC, omar-labana commented
Hi @yigitm, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 13:49 UTC, merged